//! Throwaway `config.lua` writer for the TUI simulator.
//!
//! Scenarios under the simulator need zag to talk to a local mock HTTP
//! server instead of any real provider. Rather than require a hand-written
//! config per run, the harness scaffolds a `config.lua` into a temp dir
//! that declares a single `mock` provider pointing at the mock server's
//! loopback port and sets it as the default model.
//!
//! The body is a fixed template; only the port varies. The caller decides
//! where the file lives (usually the scenario's artifacts dir) and owns
//! cleanup of the surrounding directory.

const std = @import("std");

const log = std.log.scoped(.sim_config_scaffold);

/// Template rendered at write time. `{d}` slot receives the mock port.
const config_template =
    \\-- Generated by zag-sim. Points zag at a local mock HTTP server.
    \\require("zag.providers.openai")
    \\zag.provider {{
    \\  name = "mock",
    \\  url = "http://127.0.0.1:{d}/v1/chat/completions",
    \\  wire = "openai",
    \\  auth = {{ kind = "none" }},
    \\  default_model = "mock-model",
    \\  models = {{
    \\    {{ id = "mock-model", context_window = 8192, max_output_tokens = 4096, input_per_mtok = 0, output_per_mtok = 0 }},
    \\  }},
    \\}}
    \\zag.set_default_model("mock/mock-model")
    \\
;

/// Write `<target_dir>/config.lua` defining a `mock` provider that points
/// the openai wire at the given local port. Path created if missing.
/// Caller owns `target_dir`; we don't keep a reference.
pub fn writeMockConfig(
    alloc: std.mem.Allocator,
    target_dir: []const u8,
    port: u16,
) !void {
    const abs_path = try std.fs.path.join(alloc, &.{ target_dir, "config.lua" });
    defer alloc.free(abs_path);
    try writeMockConfigAt(alloc, abs_path, port);
}

/// Same, but write to a specific absolute path instead of `<dir>/config.lua`.
pub fn writeMockConfigAt(
    alloc: std.mem.Allocator,
    abs_path: []const u8,
    port: u16,
) !void {
    // Ensure the parent directory exists; callers may pass a freshly minted
    // artifacts dir with no intermediate components yet.
    if (std.fs.path.dirname(abs_path)) |parent| {
        try std.fs.cwd().makePath(parent);
    }

    const body = try std.fmt.allocPrint(alloc, config_template, .{port});
    defer alloc.free(body);

    var file = try std.fs.cwd().createFile(abs_path, .{ .truncate = true });
    defer file.close();
    try file.writeAll(body);

    log.debug("wrote mock config to {s} (port={d})", .{ abs_path, port });
}

// --- tests ------------------------------------------------------------------

test "writeMockConfig writes a valid mock provider definition" {
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();
    const tmp_path = try tmp.dir.realpathAlloc(std.testing.allocator, ".");
    defer std.testing.allocator.free(tmp_path);

    try writeMockConfig(std.testing.allocator, tmp_path, 12345);

    const config_bytes = try tmp.dir.readFileAlloc(std.testing.allocator, "config.lua", 64 * 1024);
    defer std.testing.allocator.free(config_bytes);

    try std.testing.expect(std.mem.indexOf(u8, config_bytes, "require(\"zag.providers.openai\")") != null);
    try std.testing.expect(std.mem.indexOf(u8, config_bytes, "name = \"mock\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, config_bytes, "127.0.0.1:12345") != null);
    try std.testing.expect(std.mem.indexOf(u8, config_bytes, "auth = { kind = \"none\" }") != null);
    try std.testing.expect(std.mem.indexOf(u8, config_bytes, "set_default_model(\"mock/mock-model\")") != null);
}

test "writeMockConfigAt writes to an explicit absolute path" {
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();
    const tmp_path = try tmp.dir.realpathAlloc(std.testing.allocator, ".");
    defer std.testing.allocator.free(tmp_path);

    const explicit = try std.fmt.allocPrint(std.testing.allocator, "{s}/sub/cfg.lua", .{tmp_path});
    defer std.testing.allocator.free(explicit);
    // Parent doesn't exist. Function should make it.
    try writeMockConfigAt(std.testing.allocator, explicit, 8080);

    const config_bytes = try std.fs.cwd().readFileAlloc(std.testing.allocator, explicit, 64 * 1024);
    defer std.testing.allocator.free(config_bytes);
    try std.testing.expect(std.mem.indexOf(u8, config_bytes, "127.0.0.1:8080") != null);
}
